name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
    MY_NAME:
      description: "Who to greet"
      required: true
      default: "World"

# runs:
#     using: "docker"
#     image: "Dockerfile"

runs:
  using: "composite"
  steps:
    - run: echo "Hello ${{ inputs.MY_NAME }}"
      shell: bash

branding:
    icon: "mic"
    color: "purple"

