name: Hello GHA World

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v7

      # Step 2: Reference your local action path
      - name: Greet user
        uses: ./.github/actions/hello-action
        with:
          MY_NAME: "Alex"

      - name: Say hello from container
        uses: docker://hello-world:latest